CREATE TABLE IF NOT EXISTS scheduler_runs (
    task_name   VARCHAR(50) PRIMARY KEY,
    last_run_at TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
